# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='realtime-service.proto',
  package='realtime',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16realtime-service.proto\x12\x08realtime\"\x1d\n\x0cRouteRequest\x12\r\n\x05route\x18\x01 \x01(\t\"0\n\rRouteResponse\x12\x0c\n\x04json\x18\x01 \x01(\t\x12\x11\n\tfromCache\x18\x02 \x01(\x08\x32\x9e\x01\n\x0fRealtimeService\x12I\n\x12GetLatestStreaming\x12\x16.realtime.RouteRequest\x1a\x17.realtime.RouteResponse\"\x00\x30\x01\x12@\n\tGetLatest\x12\x16.realtime.RouteRequest\x1a\x17.realtime.RouteResponse\"\x00\x30\x01\x62\x06proto3')
)




_ROUTEREQUEST = _descriptor.Descriptor(
  name='RouteRequest',
  full_name='realtime.RouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='route', full_name='realtime.RouteRequest.route', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=65,
)


_ROUTERESPONSE = _descriptor.Descriptor(
  name='RouteResponse',
  full_name='realtime.RouteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='realtime.RouteResponse.json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromCache', full_name='realtime.RouteResponse.fromCache', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['RouteRequest'] = _ROUTEREQUEST
DESCRIPTOR.message_types_by_name['RouteResponse'] = _ROUTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RouteRequest = _reflection.GeneratedProtocolMessageType('RouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREQUEST,
  '__module__' : 'realtime_service_pb2'
  # @@protoc_insertion_point(class_scope:realtime.RouteRequest)
  })
_sym_db.RegisterMessage(RouteRequest)

RouteResponse = _reflection.GeneratedProtocolMessageType('RouteResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROUTERESPONSE,
  '__module__' : 'realtime_service_pb2'
  # @@protoc_insertion_point(class_scope:realtime.RouteResponse)
  })
_sym_db.RegisterMessage(RouteResponse)



_REALTIMESERVICE = _descriptor.ServiceDescriptor(
  name='RealtimeService',
  full_name='realtime.RealtimeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=118,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLatestStreaming',
    full_name='realtime.RealtimeService.GetLatestStreaming',
    index=0,
    containing_service=None,
    input_type=_ROUTEREQUEST,
    output_type=_ROUTERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLatest',
    full_name='realtime.RealtimeService.GetLatest',
    index=1,
    containing_service=None,
    input_type=_ROUTEREQUEST,
    output_type=_ROUTERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REALTIMESERVICE)

DESCRIPTOR.services_by_name['RealtimeService'] = _REALTIMESERVICE

# @@protoc_insertion_point(module_scope)
